### ISSUE TITLE
Suggestion - when nothing to display

### ISSUE THREAD

**Issue by Whooolia** [FAC-Sixteen/Week5-purple-sloths#29]
![image](https://user-images.githubusercontent.com/36998110/55619199-23db6a00-5790-11e9-8fd8-a6706511d754.png)

Since your team manages everything well, I was just wondering what would happen if I type a random thingy, and it doesn't display anything. You got the error msg on console, so it would be nice handling this case if you have extra hour before presentation! :muscle:

**Comment by dubhcait** [comment]
Thanks I think we have sorted it better now. :)
